name:                connect-four-haskell
version:             1.0.0
github:              "Baohoang555/connect-four-haskell"
license:             BSD3
author:              "Bao Hoang"
maintainer:          "hoangbaovu4@gmail.com"
copyright:           "2025 Bao Hoang"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Connect Four game with AI, networking, and GUI
category:            Game

description:         Please see the README on GitHub at <https://github.com/Baohoang555/connect-four-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- vector >= 0.12
- random >= 1.2
- mtl >= 2.2
- transformers >= 0.5
- parallel >= 3.2
- async >= 2.2
- stm >= 2.5
- network >= 3.1
- websockets >= 0.12
- aeson >= 2.0
- binary >= 0.8
- bytestring >= 0.11
- text >= 1.2
- gloss >= 1.13
- brick >= 1.0
- vty >= 5.35
- time >= 1.9
- directory >= 1.3
- filepath >= 1.4
- deepseq >= 1.4
- microlens >= 0.4
- microlens-th >= 0.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src
  exposed-modules:
  - Game.Types
  - Game.Board
  - Game.Rules
  - Game.AI
  - Game.AI.MonteCarlo
  - Game.AI.Parallel
  - Network.Protocol
  - Network.Server
  - Network.Client
  - Storage.Serialization
  - Storage.GameState
  - Storage.Statistics
  - Concurrency.GameManager
  - Concurrency.Synchronization
  - UI.Graphics
  - UI.Terminal

executables:
  connect-four-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-haskell

  connect-four-server:
    main:                Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-haskell

  connect-four-client:
    main:                Client.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-haskell

tests:
  connect-four-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-haskell
    - hspec >= 2.9
    - QuickCheck >= 2.14

benchmarks:
  connect-four-benchmark:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-haskell
    - criterion >= 1.5